<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>4b820495-d49b-400a-9d57-646acff61fad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter email address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ead11273-4623-46c7-804e-ee4df74879e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>478e2331-95bf-4134-bea8-abf4d4ac1b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>659aa82b-281a-43c6-9745-49c48f62e916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email address</value>
      <webElementGuid>009aae55-e781-4658-bac5-6cc5bf6fe787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full mt-2 text-sm pl-7 text-black bg-white bg-clip-padding  rounded transition ease-in-out m-0 inline-block h-12  font-semibold placeholder-Silver</value>
      <webElementGuid>daadb333-c40d-4cca-b7a7-fd97aafa1457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;bg-cover bg-no-repeat h-full overflow-x-hidden&quot;]/div[@class=&quot;flex flex-col flex-grow  min-h-screen&quot;]/div[2]/div[@class=&quot;grid grid-col bg-white border mx-2 md:float-right gap-1 w-auto lg:mr-14 rounded-t-2xl rounded-b-2xl lg:w-2/5 -mt-1.5&quot;]/div[@class=&quot;px-10&quot;]/div[@class=&quot;mx-10&quot;]/div[@class=&quot;relative&quot;]/form[1]/div[@class=&quot;mt-3 relative&quot;]/input[@class=&quot;form-control w-full mt-2 text-sm pl-7 text-black bg-white bg-clip-padding  rounded transition ease-in-out m-0 inline-block h-12  font-semibold placeholder-Silver&quot;]</value>
      <webElementGuid>00cce9b0-daa8-49ad-8d2a-46e9b22694ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>11b521ff-a1d9-48c1-9522-737ef1edb8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div[2]/div/form/div/input</value>
      <webElementGuid>5a6ed076-bf1e-4027-8276-065931df8630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3b8bdb1a-856d-4449-b67f-660e08fdf092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @placeholder = 'Enter email address']</value>
      <webElementGuid>e7b8fbb3-33c9-48d1-af7a-9bf8ee58d606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
