<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EngageX Campaign Manager_loginIdLoginPage</name>
   <tag></tag>
   <elementGuidId>f9dba29c-45f3-44be-9e0d-7d28cb9b6ad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginIdLoginPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginIdLoginPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Login ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fcc780b-47fd-4415-8d1f-0ec4249807d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4eade3ed-d77b-4a86-aba0-4a191e3da948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcab0926-1cf7-4b06-91a2-460e35e0ebb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginIdLoginPage</value>
      <webElementGuid>2c60ac77-f10e-497f-859c-34eee480202a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Login ID</value>
      <webElementGuid>9567d1b0-3292-4968-8e5d-0113cf53f746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[placeholder]loginId1</value>
      <webElementGuid>4099209d-e3d0-4a9f-9b7c-415f90305b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>b18606c0-56e1-4197-a010-ec12a4aa0f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17104590-9cb7-4f88-b2fb-a80a7983d7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.1.1.0.3.0.0.4</value>
      <webElementGuid>94a0edbe-04bb-4c70-87fd-b6078ac48e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginIdLoginPage&quot;)</value>
      <webElementGuid>15f82aec-79d5-44c7-a315-5a1bafb5c62f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginIdLoginPage']</value>
      <webElementGuid>5cd458ed-f557-44bf-a132-0cbafec2a444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user_portal']/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>69814668-8efe-4d0a-a98a-0281dc336757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8a6caacd-7f80-4897-80de-6180b6027de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginIdLoginPage' and @placeholder = 'Login ID']</value>
      <webElementGuid>0246f913-6786-4eff-9f62-2c5597e10acb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
